services:
  db:
    image: postgres:16-alpine
    container_name: choisir_sa_ville_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: choisir_sa_ville
    ports:
      - "5432:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d choisir_sa_ville"]
      interval: 5s
      timeout: 5s
      retries: 20
